feat: created a product table. resolves issue #6
Rodrigues-Developers/transporte-logistica pull request #15
Opened 2023-03-07 23:10 UTC by Machado21

I have created a component to product table, using another page to show it.
It's showing in home page .

2023-03-09 11:41 UTC, brunorcx requested changes

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <th>Status</th> -->
```suggestion
           
```
remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <td>{{prod.arrival_forecast | date: 'dd/MM/yyyy'}}</td> -->
```suggestion
           
```
remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <td>{{prod.date_out | date: 'dd/MM/yyyy'}}</td>             -->
```suggestion
            
```
remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <td>{{prod.pin_release | date: 'dd/MM/yyyy'}}</td> -->
```suggestion

```
remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.less
> +            top: -1px;
Is it possible to change this to remove negative numbers?

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.less
> +            bottom: -1px;
Is it possible to change this to remove negative numbers?

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <th><input type="checkbox" class="check__all"></th> -->
```suggestion

```
remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <th>Transportadora</th> -->
```suggestion

```
Remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <th>Status</th> -->
```suggestion

```
Remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <td>{{prod.emissionNf | date: 'dd/MM/yyyy'}}</td> -->
```suggestion

```
Remove comment

2023-03-09 11:41 UTC, brunorcx commented on src/app/products-tracking/products-tracking.component.html
> +            <!-- <th><input type="checkbox" id="{{prod.id}}"></th> -->
```suggestion

```
Remove comment

2023-03-16 00:01 UTC, brunorcx commented on src/app/tracking/tracking.component.less
Good job!

2023-03-16 00:03 UTC, brunorcx approved these changes

2023-03-16 00:06 UTC, brunorcx commented
Good job fixing those requested changes.

2023-03-16 00:06 UTC, merged

2023-03-16 00:07 UTC, Machado21 reviewed
fixed