Sidebar details
Rodrigues-Developers/transporte-logistica pull request #22
Opened 2023-06-09 19:14 UTC by Machado21

The sidebar details is working, when clicked in one NF-e open a sidebar with more information about the NF-e.

2023-07-29 19:08 UTC, brunorcx requested changes

2023-07-29 19:08 UTC, brunorcx commented on src/app/features/products-tracking/products-tracking.component.ts
> +    console.log(this.details);
Delete this file
```suggestion

```

2023-07-29 19:08 UTC, brunorcx commented on src/app/features/tracking/tracking.component.less
> +  right: -51vw;
Consider changing this to use flex or grid

2023-07-29 19:08 UTC, brunorcx commented on src/app/features/tracking/tracking.component.ts
> +    const data = logis; // Dados a serem passados
Change comment to english
```suggestion
    const data = logis; // Data to be sent
```

2023-07-29 19:08 UTC, brunorcx commented on src/app/shared/details/details.component.ts
> +}
Delete this
```suggestion
```

2023-08-03 15:18 UTC, Machado21 commented on src/app/shared/details/details.component.ts
> +}
Can you verify the "}", it was deleted but wasn't comment.
on the line 48.

2023-08-03 15:20 UTC, Machado21 commented on .vscode/launch.json
> +}
```suggestion
}
```

2023-08-03 15:21 UTC, Machado21 commented on src/app/shared/details/details.component.ts
> +}
```suggestion
}
```

2023-08-03 15:29 UTC, Machado21 commented on src/app/features/tracking/tracking.component.less
> +  right: -51vw;
consider resolve this in the next commits

2023-08-03 15:34 UTC, Machado21 reviewed
Ok. Consider some things to fix in the next commits, and there is a "}" that was deleted but wasn't a comment.

2023-08-03 15:34 UTC, Machado21 commented on src/app/shared/details/details.component.ts
> +
```suggestion
}
```

2023-08-03 15:54 UTC, Machado21 commented
I accept some changes and extend one.

2023-08-03 15:54 UTC, merged